// SPDX-License-Identifier: MIT

pragma solidity ^0.8.13;

// Interface generated by solface: https://github.com/moonstream-to/solface
// solface version: 0.2.3
// Interface ID: 153ab6eb
interface IAccountSystem {
	// structs

	// events
	event AccountCreated(address account, address player, string accountVersion);
	event AccountSystemCreated(string systemVersion, string accountVersion);

	// functions
	// Selector: 535e1547
	function accountVersion() external view returns (string memory);
	// Selector: 5e5c06e2
	function accounts(address ) external view returns (address);
	// Selector: 5202f437
	function calculateAccountAddress(address player) external view returns (address result);
	// Selector: 9859387b
	function createAccount(address player) external  returns (address, bool);
	// Selector: d2636902
	function systemVersion() external view returns (string memory);

	// errors
}
