// SPDX-License-Identifier: MIT

pragma solidity ^0.8.13;

// Interface generated by solface: https://github.com/moonstream-to/solface
// solface version: 0.2.3
// Interface ID: b29a221d
interface IDegenCasinoAccount {
	// structs
	struct Action0 {
		address game;
		bytes data;
		uint256 value;
		uint256 request;
	}
	struct ExecutorTerms1 {
		address[] rewardTokens;
		uint16[] basisPoints;
	}
	struct Action2 {
		address game;
		bytes data;
		uint256 value;
		uint256 request;
	}
	struct ExecutorTerms3 {
		address[] rewardTokens;
		uint16[] basisPoints;
	}
	struct Action4 {
		address game;
		bytes data;
		uint256 value;
		uint256 request;
	}
	struct ExecutorTerms5 {
		address[] rewardTokens;
		uint16[] basisPoints;
	}

	// events
	event EIP712DomainChanged();

	// functions
	// Selector: 535e1547
	function accountVersion() external view returns (string memory);
	// Selector: 6038d711
	function actionHash(Action0 memory action) external view returns (bytes32);
	// Selector: 01fa4150
	function drain(address[] memory tokenAddresses) external ;
	// Selector: 84b0196e
	function eip712Domain() external view returns (bytes1 fields, string memory name, string memory version, uint256 chainId, address verifyingContract, bytes32 salt, uint256[] memory extensions);
	// Selector: 1f66c4ff
	function executorTermsHash(ExecutorTerms1 memory terms) external view returns (bytes32);
	// Selector: cd9deaca
	function lastRequest() external view returns (uint256);
	// Selector: 99145101
	function play(Action2 memory action, ExecutorTerms3 memory terms, bytes memory playerActionSignature, bytes memory playerTermsSignature) external ;
	// Selector: f0a0a3f8
	function playInSession(Action4 memory action, ExecutorTerms5 memory terms, uint256 sessionID, uint256 expiration, bytes memory playerSessionSignature, bytes memory playerTermsSignature) external ;
	// Selector: 48db5f89
	function player() external view returns (address);
	// Selector: 294f56a6
	function sessionHash(address executor, uint256 sessionID, uint256 expiration) external view returns (bytes32);
	// Selector: de6d6d96
	function withdraw(address[] memory tokenAddresses, uint256[] memory amounts) external ;

	// errors
	error ActionFailed();
	error FailedToSendReward();
	error InvalidPlayerActionSignature();
	error InvalidPlayerTermsSignature();
	error InvalidSessionSignature();
	error InvalidShortString();
	error MismatchedArrayLengths();
	error RequestTooLow();
	error SessionExpired();
	error StringTooLong(string str);
	error Unauthorized();
	error Unsuccessful();
}
